######################################################################
# Automatically generated by qmake (3.0) ti elokuuta 18 18:29:50 2015
######################################################################

TEMPLATE = subdirs
SUBDIRS = sgserver sgclient tests

dox.target = doc
dox.commands = doxygen Doxyfile_sg
dox.depends = sgserver sgclient tests

QMAKE_EXTRA_UNIX_TARGETS += dox
