######################################################################
# Automatically generated by qmake (3.0) ti elokuuta 18 18:27:38 2015
######################################################################

isEmpty(PREFIX) {
  PREFIX = /usr/local
}

TEMPLATE = app

TARGET = sgclient
target.path = $$PREFIX/bin/

INCLUDEPATH += . ../include

QT = core gui widgets

INSTALLS += target

# Input
HEADERS += sgclient.h mainwindow.h
SOURCES += sgclient.cc mainwindow.cpp

FORMS += mainwindow.ui
